#!/usr/bin/env bash
#
# This file defines the global templates used to generate the 'index.html' and 'index.rss'
# when using `git achievements --publish`
#

############################ template for each locked list item
# used like: sprintf $template $title $content
declare -x ACHIEVEMENTSSTPL_LOCKED_ITEM=$(cat <<HTMLTPL
<li class="list-group-item"><div class="title">%s</div><div class="info">%s</div></li>
HTMLTPL
)

############################ template for each unlocked list item
# used like: sprintf $template $title $content
declare -x ACHIEVEMENTSSTPL_UNLOCKED_ITEM=$(cat <<HTMLTPL
<div class="panel panel-default"><div class="panel-heading">%s</div><div class="panel-body">%s</div></div>
HTMLTPL
)

############################ global HTML template for the 'index.html' file
# parsing vars:
# %USER%        = ${user}
# %MAILHASH%    = ${mailhash}
# %COUNT%       = ${unlockedCount}
# %TOTAL%       = ${total}
# %POINTS%      = ${points}
# %DATE%        = current date
# %COMMANDS%    = git commands list (raw text)
# %UNLOCKED%    = unlocked items list
# %LOCKED%      = locked items list
declare -x ACHIEVEMENTSSTPL_INDEX=$(cat <<HTMLTPL
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="style.css" rel="stylesheet">
    <title>%USER%'s Git Achievements</title>
    <link rel="alternate" type="application/rss+xml" title="rss feed" href="index.rss"/>
</head>
<body>
<div class="container">

    <div class="jumbotron">

        <div class="pull-left">
            <div class="header">
                <h3 class="text-muted">%USER%'s Git Achievements</h3>
            </div>
            <p class="lead">Unlocked %COUNT%/%TOTAL% <a href="http://github.com/icefox/git-achievements">Git Achievements</a> for %POINTS% points</p>
        </div>

        <div class="pull-right">
            <img src='http://www.gravatar.com/avatar/%MAILHASH%' alt='_'/>
        </div>

        <div class="clearfix"></div>
    </div>

    <div class="marketing">
        %UNLOCKED%
        <p>Git commands sorted by usage:</p>
        <pre style="text-align: left">
%COMMANDS%
        </pre>
        <p>
            <a id="showlocked" href="javascript:showLocked()">Show locked Achievements</a>
            <a id="hidelocked" href="javascript:hideLocked()">Hide locked Achievements</a>
        </p>
        <div id="locked">
            There are %TOTAL% Achievements. Some achievements can be leveled up depending on the number of times it is used (Used 2 times = level 1, 4 = level 2, 8 = level 3, 16 = level 4, 32 = level 5, etc)
            <ul class="list-group">
                %LOCKED%
            </ul>
        </div>

        <footer class="footer small">
            <ul>
                <li>generated at %DATE%</li>
                <li>original sources at <a href="https://github.com/%USER%/git-achievements">https://github.com/%USER%/git-achievements</a></li>
                <li>fired by <a href="https://github.com/icefox/git-achievements">icefox</a></li>
                <li>styles by <a href="http://bootswatch.com/slate/">Bootswatch</a> with <a href="http://getbootstrap.com">Bootstrap</a></li>
            </ul>
        </footer>

    </div>

</div>
<script type="text/javascript">
function showBlock(id) {
    var block = document.getElementById(id);
    if (block) {
        block.style.visibility = 'visible';
        block.style.display = 'block';
    }
}
function hideBlock(id) {
    var block = document.getElementById(id);
    if (block) {
        block.style.visibility = 'hidden';
        block.style.display = 'none';
    }
}
function showLocked() {
    showBlock('locked');
    showBlock('hidelocked');
    hideBlock('showlocked');
}
function hideLocked() {
    hideBlock('locked');
    hideBlock('hidelocked');
    showBlock('showlocked');
}
hideLocked();
</script>
</body></html>
HTMLTPL
)

############################ global RSS template for the 'index.rss' file
# parsing vars:
# %USER%        = ${user}
# %MAILHASH%    = ${mailhash}
# %COUNT%       = ${unlockedCount}
# %TOTAL%       = ${total}
# %POINTS%      = ${points}
# %DATE%        = current date
# %UNLOCKED%    = unlocked items list
declare -x ACHIEVEMENTSSTPL_RSS=$(cat <<HTMLTPL
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0">
<channel>
<title>%USER% - Git Achievements</title>
<description>Unlocked %COUNT%/%TOTAL% Git Achievements for %POINTS% points</description>
<link>https://github.com/%USER%</link>
%UNLOCKED%
</channel>
</rss>
HTMLTPL
)
